---
title: "About"
author: "Colin Mahony"
date: "26/11/2021"
output: html_document
---

### About this app

The goal of this app is to help users to better understand the global climate model ensemble featured in Version 7 of <a href="http://climatena.ca/" target="_blank">ClimateNA</a>. These models are from the new generation of global climate model simulations, the sixth Coupled Model Intercomparison Project (CMIP6; <a href="https://gmd.copernicus.org/articles/9/1937/2016/gmd-9-1937-2016.pdf" target="_blank">Eyring et al. 2016</a>), which will be featured in the upcoming 2021 IPCC sixth assessment report (AR6). CarbonBrief provides a good <a href="https://www.carbonbrief.org/cmip6-the-next-generation-of-climate-models-explained" target="_blank">explanation</a> of CMIP6 and the global results. 

#### Contributors
App created by:<br>
Colin Mahony<br>
Research Climatologist<br>
British Columbia Ministry of Forests, Lands, Natural Resource Operations and Rural Development<br>
colin.mahony@gov.bc.ca

CMIP6 data downloaded by Tongli Wang, Associate Professor at the UBC Department of Forest and Conservation Sciences

### Methods

**Climate Variables**--There are three climate elements available: Mean daily maximum temperature (T<sub>max</sub>), mean daily minimum temperature (T<sub>min</sub>), and precipitation (PPT). Other variables available in ClimateNA are derived from these variables.

**Emissions scenarios**--This app features climate model simulations from the ScenarioMIP project, which produces projections of future climate change based on scenarios called <a href="https://www.carbonbrief.org/explainer-how-shared-socioeconomic-pathways-explore-future-climate-change" target="_blank">Shared Socioeconomic Pathways</a>. This app features the four major ScenarioMIP SSPs: SSP1-2.6, SSP2-4.5, SSP3-7.0, and SSP5-8.5.  SSP1-2.6 assumes strong emissions reductions (mitigation) roughly consistent with the goals of the Paris Climate Accords to limit global warming to 2<sup>o</sup>C above pre-industrial temperatures. SSP2-4.5 assumes moderate mitigation roughly consistent with current emissions policies and economic trends. SSP3-7.0 is representative of a broader range of "baseline" scenarios that assume the absence of mitigation policies, and is associated with linear increase in the rate of greenhouse gas emissions. SSP5-8.5 is at the high end of the baseline scenarios, and rapid expansion of greenhouse gas emissions over the next several decades and end-of-century emissions more than three times higher than current emissions [Riahi et al. 2017](https://www.sciencedirect.com/science/article/pii/S0959378016300681). The SSPs begin in 2015; from 1850 to 2014, the climate models are run using historically observed emissions from natural (e.g., volcanoes) and human sources.  

**Regional averages**--There is essentially no downscaling in this app. All climate model data were bilinearly interpolated to a common 0.5^o grid derived from the 025^o ERA5 grid (shown in the model topography maps in the Maps tab). Plot values are the average of the grid points across North America or the user-selected IPCC regions.

#### The Time Series tab

This tab allows users to compare model simulations to each other and to observations, and to produce customized exportable plots. 

**Ensemble range**--There are several simulation runs for each climate model. This app shows the range of these runs i.e., the minimum and maximum of the model runs in each year of the time series. The "Model Info" tab specifies the number of runs for each model. 

**Bias correction**--Bias correction is an option, defaulted "on", since one of the purposes of this app is to assess regional bias in each model and across the ensemble. When bias correction is turned on, each single-model ensemble is shifted so that its 1961-1990 ensemble mean matches the 1961-1990 mean of the observed time series. Bias correction is done by addition for temperature and multiplication for precipitation.  

**Compiled ensembles**--Users can compile selected models into a multi-model ensemble. In these plots, the shaded envelope shows the maxima and minima of all the single-model ensembles collectively, and the multimodel ensemble mean is the mean of the single-model ensemble means. 

**Station observations**--Station observations are available from two sources. The default station-based observational time series are obtained from the Climatic Research Unit (CRU TS v4.05; <a href="https://doi.org/10.1038/s41597-020-0453-3" target="_blank">Harris et al. 2020</a>) for temperature and the Global Precipitation Climatology Centre (GPCC; <a href="https://doi.org/10.5676/DWD_GPCC/FD_M_V2020_050" target="_blank">Schneider et al. 2020</a>) for precipitation. The observed historical time series from <a href="http://climatena.ca/" target="_blank">ClimateNA</a> are generated from the gridpoints of the common grid shown in Topography mode of the Maps tab. Both sources are spatial averages of weather station observations using different methods. The absolute baseline values of the different observational data sets are not expected to agree, since they account for elevation in different ways. However, differences among the observational datasets in anomalies and trends are of interest. 

**ERA5 reanalysis**--A <a href="https://www.ecmwf.int/en/about/media-centre/focus/2020/fact-sheet-reanalysis" target="_blank">reanalysis</a> is a global weather model calibrated to observations. ERA5 is the state-of-the-art global reanalysis provided by the European Centre for Medium-Range Weather Forecasts <a href="https://rmets.onlinelibrary.wiley.com/doi/full/10.1002/qj.3803" target="_blank">(Hersbach et al. 2020)</a>. The ERA5 time series is provided to indicate the degree to which the gridding method in this app is a valid basis for comparing absolute climate conditions from models and observations. 

#### The Choose Models tab

This tab allows users to understand the differences among models in a plot of projected climate changes in two variables. The main application of this tab is selection of small ensembles for regional analysis. Plot values are the average of the changes in all of the 0.5^o grid points within the boundaries of North America or the user-selected subregion. 

**Calculation of change**--Change in climate variables for each model is calculated relative to the model's simulated mean climate of the 1961-1990 reference period. This reference period mean is calculated from all available historical runs for each model. The change in each variable is the mean of all projected runs for the model within each scenario. Calculating change from multiple runs for each scenario reduces the uncertainty in the climate change signal due to natural variability. The interpolation lines connecting the points for each model are simply visual aids and are not generated by the models. 

**Predefined order for reducing ensemble size**--In "Predefined" ensemble selection mode, models are excluded in two phases: first based on screening criteria to exclude models with lower value for the anticipated uses of ClimateNA data and second using the method of <a href="https://journals.ametsoc.org/view/journals/clim/28/3/jcli-d-14-00636.1.xml" target="_blank">Cannon (2015)</a> to best represent the range of climate changes in the remaining models. See the section "Predefined subsets of the ClimateNA CMIP6 ensemble" below for more details. 

**IPCC regions**--Plot summaries are provided for the full area of North America or for eight regions defined by the Intergovernmental Panel on Climate Change <a href="https://www.researchgate.net/publication/340387533_An_update_of_IPCC_climate_reference_regions_for_subcontinental_analysis_of_climate_model_data_Definition_and_aggregated_datasets" target="_blank">(Iturbide et al. 2020)</a>. 

**Data download**--The "download data" button downloads the full data table (all models/periods/scenarios/variables) of changes for the selected IPCC region. The first row of the table is the 1961-1990 reference period; it is zero for all variables since this is the baseline against which changes are measured. 

#### The Maps tab

This tab primarily displays maps of climate change relative to the 1961-1990 reference period. These change values are calculated with the same method as the change values plotted in the Choose Models tab. The maps are created using the raw climate model data, and show the grid resolution of each climate model. For reference, this tab also displays the model topography, i.e., the elevation assigned to each grid cell. The final panel of the elevation maps shows the 0.5^o "common grid" that all global climate models were interpolated to for calculation of the data plotted in the other tabs.  

### Selection of the ClimateNA CMIP6 ensemble

The goal of model selection for ClimateNA was to select a set of approximately 15 models that represent the CMIP6 ensemble. The selection criteria reflect that ClimateNA are primarily designed for downscaling of monthly climate normals (30-year averages): The emphasis is on representing the climate change signal produced by each model rather than on representing internal variability (model weather). From the ESGF ScenarioMIP data holdings current to December 2020, we excluded models sequentially based on 6 criteria: 

**Criterion 1: Minimum of 3 historical runs available.** This criterion ensures robust bias correction. Bias correction in ClimateNA is performed using the delta method: in which each model’s simulations are adjusted to remove the difference (delta factor) between the simulated and observed climate during the 1961-1990 reference period. Calculating the delta factor from the mean of at least three simulations reduces the confounding influence of the internal variability of individual runs on bias correction. 44 ScenarioMIP models passed this criterion. 

**Criterion 2: T<sub>min</sub> and T<sub>max</sub> available.** T<sub>min</sub> and T<sub>max</sub> are basic climate variables for ClimateBC and ClimateNA. Any models that do not provide these variables are incompatible with ClimateBC. 10 models failed this criterion. Notably, CESM2 does provide T<sub>min</sub> and T<sub>max</sub> in their future projections, but due to an archiving error these variables are not available for the historical runs of this model. 

**Criterion 3. Complete scenarios.** Models need to have at least one simulation of each of the four major SSP marker scenarios (SSP1-2.6, SSP2-4.5, SSP3-7.0, and SSP5-8.5). eight models failed this criterion. 

**Criterion 4. One model per institution.** This criterion is a widely applied best practice in ensemble selection <a href="https://journals.ametsoc.org/view/journals/clim/29/23/jcli-d-15-0761.1.xml" target="_blank">(Leduc et al. 2016)</a>. The rationale for each selection is provided below. 
*	CNRM-ESM2-1 (ECS 4.8^(o)C) was chosen over CNRM-CM6-1 (ECS 4.9^(o)C) to give preference to the ESM over the AOGCM configuration; 
*	EC-Earth3 (ECS 4.3^(o)C) was arbitrarily chosen over EC-Earth3-Veg (ECS 4.3^(o)C);
*	INM-CM5-0 (ECS 1.9^(o)C) was arbitrarily chosen over INM-CM4-8 (ECS 1.8^(o)C); 
*	MPI-ESM1-2-HR (ECS 3.0^(o)C) was chosen over MPI-ESM1-2-LR (ECS 3.0^(o)C) due to its high resolution and availability of >1 run for all but SSP5-8.5. 
*	MIROC6 (ECS 2.6^(o)C) was chosen over MIROC-ES2L (ECS 2.7^(o)C) because it has more runs/scenario, higher resolution, and because the latter has very high temperature bias over British Columbia. 
*	For the purposes of this ensemble, different physics or forcing schemes were considered different models. We used only the r*i1p3f1 variants of the GISS-E2-1-G model, as these had the most complete set of scenario simulations. 

**Criterion 5. No closely related models.** Models that share components were excluded, following Figure 5 of <a href="https://esd.copernicus.org/articles/11/995/2020/esd-11-995-2020.pdf" target="_blank">Brunner et al. (2020)</a>. NESM3 was excluded due to its close relation to MPI-ESM1.  

**Criterion 6. No large biases.** Bias correction as performed in ClimateNA disrupts the physical connection between climate variables, and these distortions increase with the size of the biases in the simulation. For this reason, models with small biases are preferable to models with large biases, all else being equal. In an assessment over British Columbia, the AWI-CM-1-1-MR showed extreme temperature biases that warranted exclusion from the ensemble. 

To provide context, this app includes all 19 models that met criteria 1-3 as of December 2020. 

The 13-model ensemble has a mean global equilibrium climate sensitivity (ECS) of 3.7^(o)C and a range of 1.9-5.6^(o)C, which matches the full CMIP6 ensemble ECS (3.7^(o)C; 1.8-5.6^(o)C, <a href="https://advances.sciencemag.org/content/advances/6/26/eaba1981.full.pdf" target="_blank">Meehl et al. 2020</a>). 

### Predefined subsets of the ClimateNA CMIP6 ensemble

The 13 ClimateNA models are a valid ensemble. However, some analysts may wish or need to use a lesser number of models in their analyses. To provide guidance on selecting from among the 13 models provided in ClimateBC, the "Choose models" tab of this tool offers a predefined order of exclusion of models for user-specified ensemble sizes. Models are excluded in two phases: first based on screening criteria to exclude models with lower value for the anticipated uses of ClimateBC data and second using the method of <a href="https://journals.ametsoc.org/view/journals/clim/28/3/jcli-d-14-00636.1.xml" target="_blank">Cannon (2015)</a> to best represent the range of climate changes in the remaining models. 

The following four screening criteria are more subjective than the six criteria used to select the 13-member ensemble. They generally are not sufficient in isolation but the balance of the criteria provides some justification for model exclusions. 

**Criterion 7. Constraints on equilibrium climate sensitivity (ECS).** Multiple lines of evidence indicate that the Earth’s equilibrium climate sensitivity (ECS) is very likely between 2<sup>o</sup>C and 5<sup>o</sup>C (<a href="https://advances.sciencemag.org/content/advances/6/12/eaaz9549.full.pdf" target="_blank">Tokarska et al. 2020</a>; <a href="https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/2019GL086757" target="_blank">Liang et al. 2020</a>; <a href="https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2019RG000678?fbclid=IwAR0RaslfRZtPcbi_RjZS3wnHWralh0GuoMyJ9NSbgAOOezP0VyTHgrfdlrs" target="_blank">Sherwood et al. 2020</a>). The evidence for the lower bound is robust, and weaker for the upper bound. From one perspective, inclusion of models with ECS outside this range uneccessarily increases the modeling uncertainty in downstream analyses. The opposing perspective is that high-sensitivity models are useful as a representation of high-impact, low-likelihood scenarios ([Sutton and Hawkins 2020](https://esd.copernicus.org/articles/11/751/2020/)). Both perspectives are valid, and the preference depends on the objectives of each analysis. 

**Criterion 8. Model resolution.** Four of the ClimateNA models are high enough resolution to resolve macrotopography e.g., to clearly differentiate the coast mountains from the Columbia/Rocky Mountains. This resolved macrotopography does produce elevation-dependent climate change signals and rainshadow effects. These models are weighted towards inclusion despite other criteria such as a low number of simulations per scenario. Conversely, models with very low resolution are weighted towards exclusion. 

**Criterion 9. Number of simulation runs.** ClimateNA is primarily designed for analysis of projected climate normals; the climate change signal is of primary interest. Internal variability of the models are a confounding factor, producing erratic climate change trajectories in noisy climate variables like precipitation and winter temperature. The signal-to-noise ratio is increased by averaging the projected normals over multiple simulations of the same emissions scenario. Four models (BCC, INM, GFDL, and MRI) have only one run for most of the four scenarios, and this is a consideration for their exclusion. 

**Criterion 10: Spatial pattern.** IPSL-CM6A-LR has a pronounced pattern of localized summer heating along the BC coast ranges, and little warming in some adjacent cells. This pattern is present for both Tmin and Tmax for all summer months. This may be a physically credible response within the model context, for example due to a snow albedo feedback. However, for the purposes of ClimateBC it would be problematic to downscale this warming pattern across all elevations within the cell. This problem is not isolated to IPSL-CM6A-LR, but the cell-to-cell contrast is especially pronounced in IPSL and could create artefacts for analyses based on ClimateBC. 

The following models are excluded based on the combination of the four screening criteria: 

1. CanESM5, because its very low horizontal resolution creates grid-box artefacts in downscaling and because its very high climate sensitivity (ECS 5.6<sup>o</sup>C) is also represented by UKESM1-0-LL.  

2. INM-CM5-0, because it has very low climate sensitivity (ECS 1.9<sup>o</sup>C) and is an outlier among CMIP6 models for under-representing the observed 1975-2014 global temperature trend (<a href="https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/2019GL086757" target="_blank">Liang et al. 2020</a>). In addition, this model has only one simulation for most scenarios, producing a less robust climate signal. 

3. BCC-CSM2-MR, due to having a single simulation for each scenario and very low topographic resolution. 

4. IPSL-CM6A-LR, due to isolated grid cells with very high summer warming in the BC Coast Ranges. The warming in these cells may be physically plausible (e.g., due to snow albedo feedbacks) in the model's simplified topography, but is problematic for downscaling to high spatial resolution in ClimateNA.

A fifth model, UKESM1-0-LL, also has very high climate sensitivity, similar to CanESM5, that is assessed as very unlikely based on observational evidence. Some researchers may wish to constrain their analysis ensemble to observations by excluding this model. Others may wish to include this model in their ensembles as a representation of the long tail of uncertainty in the upper limit of climate sensitivity (<a href="https://www.researchgate.net/publication/328079274_ESD_Ideas_A_simple_proposal_to_improve_the_contribution_of_IPCC_WGI_to_the_assessment_and_communication_of_climate_change_risks" target="_blank">Sutton 2018</a>). To accomodate both perspectives, we provide the option to include or exclude UKESM1-0-LL in the ordered ensemble subsets (the default is to include it). 

The 8-model subset has a mean global ECS of 3.4^(o)C (2.6-4.8^(o)C). The 9-model subset that includes UKESM1-0-LL has a mean global ECS of 3.6^(o)C (2.6-5.4^(o)C). 

After exclusion of models using the screening criteria above, subsets of the remaining eight models (plus optional UKESM1-0-LL) are provided using the method of <a href="https://journals.ametsoc.org/view/journals/clim/28/3/jcli-d-14-00636.1.xml" target="_blank">Cannon (2015)</a>. For each user-selected ensemble size, this method selects the models that span as large a range of climate changes as possible. The implementation of this method in this app used the mean of the z-standardized seasonal changes in Tmin, Tmax, and precipitation in all 20-year time periods and emissions scenarios (except SSP5-8.5). The order of model selection is unique to each IPCC region because the relative change projected by the models differs across the continent

### Guidance for selecting models, scenarios, and time periods

#### Model selection

There is broad agreement that an ensemble of at least eight independent climate models are required to represent modeling uncertainties about climate change outcomes over large regions ([Pierce et al. 2009](https://www.pnas.org/content/106/21/8441), [McSweeney et al. 2014](https://link.springer.com/article/10.1007/s00382-014-2418-8), [Cannon 2015](https://journals.ametsoc.org/view/journals/clim/28/3/jcli-d-14-00636.1.xml), [Wilcke and Bärring 2016](https://www.sciencedirect.com/science/article/pii/S1364815216300020)). Smaller ensembles (<8 models) are less likely to span the range of climate changes in all variables, and should be used with caution. However, small ensembles of 3-5 GCMs may be adequate for studies that are limited to a small area or a single time of year. Users interested in a small ensemble for specific climate variables are advised to select a custom ensemble based on visual inspection of the "Choose models" tab. If a single representative projection is desired, the 13-GCM ensemble mean is likely more reliable than any single GCM projection ([Pierce et al. 2009](https://www.pnas.org/content/106/21/8441)). 

#### Scenario selection

CMIP6 climate projections follow scenarios of future greenhouse gas emissions called [Shared Socioeconomic Pathways](https://www.carbonbrief.org/explainer-how-shared-socioeconomic-pathways-explore-future-climate-change) (SSPs). Collectively, SSP1-2.6, SSP2-4.5, and SSP3-7.0 provide a reasonable representation of optimistic, neutral, and pessimistic outlooks on global emissions policies and socioeconomic development. Where possible, we recommend using all three scenarios to represent scenario uncertainty in climate change projections. SSP2-4.5 alone is sufficient for studies focused on the near future (the 2021-2040 period) since there is only minor differentiation between the three recommended emissions scenarios in this period relative to differences between climate models. We recommend against using SSP5-8.5 for impacts and adaptation research because the emissions pathway described by SSP5-8.5 is extremely unlikely based on constraints to the supply ([Ritchie and Dowlatabadi 2017](https://www.sciencedirect.com/science/article/abs/pii/S0360544217314597)) and demand ([Ritchie and Dowlatabadi 2018](https://iopscience.iop.org/article/10.1088/1748-9326/aaa494)) for high-carbon energy sources and current trends in energy economics and policy ([Burgess et al. 2021](https://iopscience.iop.org/article/10.1088/1748-9326/abcdd2), [Hausfather and Peters 2020](https://www.nature.com/articles/d41586-020-00177-3)). 

#### Time period selection
ClimateNA traditionally summarizes future GCM projections averaged over three 30-year periods: 2011-2040 (the “2020s”); 2041-2070 (the “2050s”); and 2071-2100 (the “2080s”). Version 7 now also includes a set of five 20-year periods for the 21st Century: 2001-2020, 2021-2040, and so on. These 20-year periods provide a cleaner differentiation between the past (pre-2021) and the future (post-2020). The 2001-2020 period also provides the opportunity for direct comparison of model simulations vs. observations, which can give important context to interpretations of future projections. ClimateNA normals for the 2001-2020 period are calulated from the historical model runs for the years 2001-2014 and the SSP scenario runs for the year 2015-2020.

When interpreting projections for the near future, it is important to recognize that GCM projections are not predictions. GCM runs used for climate change projections are initiated in the 1850s and are not directly constrained by observed climate conditions. Consequently, GCM projections are essentially as uncertain for next year as they are for 20 years into the future. Decadal climate prediction, which is analogous to weather prediction for timescales of 1-10 years, is an emerging but not yet operational science that may help to reduce the uncertainty of near-term projections ([Boer et al. 2016](https://gmd.copernicus.org/articles/9/3751/2016/)). In the meantime, it is considered best practice to use an ensemble of climate projections, such as those provided by ClimateBC, for near-term regional climate change studies ([Brekke et al. 2008](https://link.springer.com/article/10.1007/s10584-007-9388-3), [Knutti 2008](https://royalsocietypublishing.org/doi/10.1098/rsta.2008.0169), [Pierce et al. 2009](https://www.pnas.org/content/106/21/8441)). Given that the recent observed climate may differ substantially from the ensemble mean, and even be outside the ensemble range, climate change adaptation decisions for the near-term (1-10 years) should carefully consider recent observed trends in addition to climate model simulations. 


### Acknowledgements

We acknowledge the World Climate Research Programme, which, through its Working Group on Coupled Modelling, coordinated and promoted CMIP6. We thank the climate modeling groups for producing and making available their model output, the Earth System Grid Federation (ESGF) for archiving the data and providing access, and the multiple funding agencies who support CMIP6 and ESGF. We also thank the European Centre for Medium-Range Weather Forecasts (ECMWF) for providing the ERA5 reanalysis via the Copernicus Climate Change Service. 
